CS

diff --git a/templates/default/unicorn/init.erb b/templates/default/unicorn/init.erb
--- a/templates/default/unicorn/init.erb
+++ b/templates/default/unicorn/init.erb
@@ -1,13 +1,106 @@
-#!/bin/bash
+#!/bin/sh
 #
-# Written by Patrick McKenzie, 2010.
-# I release this work unto the public domain.
+# init.d script for single or multiple unicorn installations. Expects at least one .conf 
+# file in /etc/unicorn
 #
-# sinatra      Startup script for Sinatra server.
-# description: Starts Sinatra as an unprivileged user.
+# Modified by jay@gooby.org http://github.com/jaygooby
+# based on http://gist.github.com/308216 by http://github.com/mguterl
 #
+## A sample /etc/unicorn/my_app.conf
+## 
+## RAILS_ENV=production
+## RAILS_ROOT=/var/apps/www/my_app/current
+#
+# This configures a unicorn master for your app at /var/apps/www/my_app/current running in
+# production mode. It will read config/unicorn.rb for further set up. 
+#
+# You should ensure different ports or sockets are set in each config/unicorn.rb if
+# you are running more than one master concurrently.
+#
+# If you call this script without any config parameters, it will attempt to run the
+# init command for all your unicorn configurations listed in /etc/unicorn/*.conf
+#
+# /etc/init.d/unicorn start # starts all unicorns
+#
+# If you specify a particular config, it will only operate on that one
+#
+# /etc/init.d/unicorn start /etc/unicorn/my_app.conf
 
-cd <%= @site_dir %> && <%= node[:bundle_path] %> exec <%= @unicorn_path %> -D -c <%= @config_file %>
-RETVAL=$?
+set -e
 
-exit $RETVAL
+sig () {
+  test -s "$PID" && kill -$1 `cat "$PID"`
+}
+
+oldsig () {
+  test -s "$OLD_PID" && kill -$1 `cat "$OLD_PID"`
+}
+
+start () {
+  cd <%= @site_dir %> && <%= node[:bundle_path] %> exec <%= @unicorn_path %> -D -c <%= @config_file %>
+}
+
+
+# Possible args:
+# $CMD
+# $OLD_PID
+cmd () {
+
+  case $1 in
+    start)
+      sig 0 && echo >&2 "Already running" && exit 0
+      echo "Starting"
+      start
+      ;;  
+    stop)
+      sig QUIT && echo "Stopping" && exit 0
+      echo >&2 "Not running"
+      ;;  
+    force-stop)
+      sig TERM && echo "Forcing a stop" && exit 0
+      echo >&2 "Not running"
+      ;;  
+    restart)
+      sig QUIT && echo "Stopping" && sleep 2
+      sig 0 && sleep 2 && sig 0 && sleep 2 && sig 0 && echo >&2 "Already running" && exit 0
+      echo "Starting <%= @site %>"
+      start
+      ;;  
+    restartx|reloadx)
+      sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
+      echo >&2 "Couldn't reload, starting '$CMD' instead"
+      $CMD
+      ;;  
+    upgrade)
+      sig USR2 && echo Upgraded && exit 0
+      echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+      $CMD
+      ;;  
+    rotate)
+            sig USR1 && echo rotated logs OK && exit 0
+            echo >&2 "Couldn't rotate logs" && exit 1
+            ;;  
+    *)  
+      echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
+      exit 1
+      ;;  
+    esac
+}
+
+setup () {
+
+  echo -n "<%= @site_dir %>: "  
+  cd <%= @site_dir %> || exit 1
+  export PID=<%= @pid_file %>
+  export OLD_PID="$PID.oldbin"
+
+}
+
+start_stop () {
+
+  setup
+  cmd $1
+  
+}
+
+start_stop $1
